name: popsycle
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy>=1.24.3
  - matplotlib>=3.7.1
  - astropy>=5.3
  - h5py>=3.8.0
  - scipy>=1.10.1
  - pyyaml>=6.0
  - pandas>=1.5.2
  - pysynphot>=2.0.0
  - synphot>=1.7.0
  - stsynphot>=1.5.1
  - scikit-learn
  - celerite
  - jplephem
  - ephem
  - pytest>=7.2.0
  - numpydoc>=1.5
  - sphinx_rtd_theme
  - pip:
      - --editable .
# Install SPISEA separately in this environment after creation.
