import pandas as pd
import numpy as np
from astropy.table import Table

def trim_popsycle_tables(idx, event_tab, comps_tab, lcurv_tab):
    """
    Trim down PopSyCLE event, companions, and lightcurve tables
    to contain only those with the specified indices=idx.
    
    The companions and lightcurve tables are matched against the
    trimmed event table's obj_id_L + obj_id_S.

    Inputs
    ------
    idx : array, ints
        indices returned from a where statement.
    event_tab : astropy.table
        PopSyCLE events table.
    comps_tab : astropy.table
        PopSyCLE companions table.
    lcurve_tab : astropy.table
        PopSyCLE lightcurves table.
    
    This code was generated by Gemini AI and edited by J. Lu.
    """
    import pandas as pd
    import numpy as np

    # --- Step 1: Convert to pandas DataFrames and apply initial trim ---
    # Convert the tables to pandas DataFrames for faster operations
    event_df = event_tab.to_pandas()
    comps_df = comps_tab.to_pandas()
    lcurv_df = lcurv_tab.to_pandas()

    # Apply the initial index trim
    event_df_t = event_df.iloc[idx].copy() # Use iloc for index-based selection

    # --- Step 2: Create a DataFrame of the keys to search for ---
    # This is the list of unique (obj_id_L, obj_id_S) pairs we are interested in
    search_keys = event_df_t[['obj_id_L', 'obj_id_S']].drop_duplicates().copy()

    # --- Step 3: Vectorized filtering using merge or isin() (Recommended) ---
    # The most efficient way is to create a combined key and use isin()
    # Create a combined key column for comparison (e.g., 'key_L_S')
    # Convert columns to string and concatenate them
    search_keys['key_L_S'] = search_keys['obj_id_L'].astype(str) + '_' + search_keys['obj_id_S'].astype(str)
    comps_df['key_L_S'] = comps_df['obj_id_L'].astype(int).astype(str) + '_' + comps_df['obj_id_S'].astype(int).astype(str)
    lcurv_df['key_L_S'] = lcurv_df['obj_id_L'].astype(int).astype(str) + '_' + lcurv_df['obj_id_S'].astype(int).astype(str)

    # Filter the tables using the isin() method on the combined key
    print(len(comps_df), len(lcurv_df))
    comps_df_t = comps_df[comps_df['key_L_S'].isin(search_keys['key_L_S'])]
    lcurv_df_t = lcurv_df[lcurv_df['key_L_S'].isin(search_keys['key_L_S'])]

    # --- Step 4 (Optional): Clean up and convert back to Astropy Table if needed ---
    # Remove the temporary key column
    comps_df_t = comps_df_t.drop(columns=['key_L_S'])
    lcurv_df_t = lcurv_df_t.drop(columns=['key_L_S'])

    # If the result must be an Astropy Table:
    # from astropy.table import Table
    event_tab_t = Table.from_pandas(event_df_t)
    comps_tab_t = Table.from_pandas(comps_df_t)
    lcurv_tab_t = Table.from_pandas(lcurv_df_t)
    
    return event_tab_t, comps_tab_t, lcurv_tab_t
